library verilog;
use verilog.vl_types.all;
entity data_path is
    port(
        CLK             : in     vl_logic;
        mCLK            : in     vl_logic;
        WEN             : in     vl_logic;
        EN              : in     vl_logic;
        CLR_A           : in     vl_logic;
        LD_A            : in     vl_logic;
        CLR_B           : in     vl_logic;
        LD_B            : in     vl_logic;
        CLR_C           : in     vl_logic;
        LD_C            : in     vl_logic;
        CLR_Z           : in     vl_logic;
        LD_Z            : in     vl_logic;
        CLR_PC          : in     vl_logic;
        LD_PC           : in     vl_logic;
        CLR_IR          : in     vl_logic;
        LD_IR           : in     vl_logic;
        OUT_A           : out    vl_logic_vector(31 downto 0);
        OUT_B           : out    vl_logic_vector(31 downto 0);
        OUT_C           : out    vl_logic;
        OUT_Z           : out    vl_logic;
        OUT_PC          : out    vl_logic_vector(31 downto 0);
        OUT_IR          : out    vl_logic_vector(31 downto 0);
        INC_PC          : in     vl_logic;
        ADDR_OUT        : out    vl_logic_vector(31 downto 0);
        DATA_IN         : in     vl_logic_vector(31 downto 0);
        DATA_BUS        : out    vl_logic_vector(31 downto 0);
        MEM_OUT         : out    vl_logic_vector(31 downto 0);
        MEM_IN          : out    vl_logic_vector(31 downto 0);
        MEM_ADDR        : out    vl_logic_vector(7 downto 0);
        DATA_MUX        : in     vl_logic_vector(1 downto 0);
        REG_MUX         : in     vl_logic;
        A_MUX           : in     vl_logic;
        B_MUX           : in     vl_logic;
        IM_MUX1         : in     vl_logic;
        IM_MUX2         : in     vl_logic_vector(1 downto 0);
        ALU_OP          : in     vl_logic_vector(2 downto 0)
    );
end data_path;
